name: shellcheck
on: [push, pull_request]
jobs:
  sh:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ludeeus/action-shellcheck@2.0.0
        with:
          scandir: ./scripts
          severity: error    # <- fail only on errors; warnings (e.g., SC2024) won't fail the job
